# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_parentID', models.IntegerField(blank=True, default=0, null=True)),
                ('dept_order', models.IntegerField(blank=True, null=True)),
                ('dept_flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 't_department',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_menus',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 't_roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_account', models.CharField(max_length=20, unique=True)),
                ('u_pwd', models.CharField(max_length=50)),
                ('u_userName', models.CharField(max_length=20)),
                ('u_dept', models.CharField(blank=True, max_length=30, null=True)),
                ('u_position', models.CharField(blank=True, max_length=20, null=True)),
                ('u_tel', models.CharField(blank=True, max_length=5, null=True)),
                ('u_email', models.CharField(blank=True, max_length=30, null=True)),
                ('u_loginChPwd', models.IntegerField(default=0)),
                ('u_enabled', models.IntegerField(default=0)),
                ('u_flag', models.IntegerField(default=0)),
                ('u_lastLogin', models.DateTimeField(blank=True, null=True)),
                ('u_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Roles')),
            ],
            options={
                'db_table': 't_users',
            },
        ),
    ]
