# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='u_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Department'),
        ),
    ]
