# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20160723_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='m_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menus',
            name='m_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='m_parentID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Roles'),
        ),
    ]
