# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0003_auto_20160723_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', models.CharField(max_length=50)),
                ('log_active', models.CharField(blank=True, max_length=50, null=True)),
                ('log_operater', models.CharField(max_length=20)),
                ('log_time', models.DateTimeField()),
                ('log_IP', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 't_log',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, unique=True)),
                ('pro_flag', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 't_providers',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='u_lastIP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
