# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0005_menus_m_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='u_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='system.Department'),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
