# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20160727_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='log_active',
            new_name='log_action',
        ),
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 27, 20, 29, 9, 638000)),
        ),
    ]
