# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20160802_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 2, 21, 15, 58, 223000)),
        ),
    ]
