# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20160824_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providers',
            old_name='pro_flag',
            new_name='pro_delflag',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='u_flag',
            new_name='u_delflag',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_flag',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='m_flag',
        ),
        migrations.AddField(
            model_name='department',
            name='dept_delflag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='m_delflag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='r_authority',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='r_delflag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 20, 49, 42, 408000)),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_dept',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
