# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 20:45
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0017_auto_20160829_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='r_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 20, 45, 24, 27000)),
        ),
    ]
