# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20160902_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 14, 43, 26, 448000)),
        ),
    ]
