# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, unique=True)),
                ('brand_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cata_name', models.CharField(max_length=30, unique=True)),
                ('cata_order', models.IntegerField(blank=True, null=True)),
                ('cata_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'catagory',
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='ass_enabled',
            field=models.IntegerField(default=0),
        ),
    ]
