# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0002_auto_20160723_2147'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assets',
            table='t_assets',
        ),
        migrations.AlterModelTable(
            name='assets_detail',
            table='t_assets_detail',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='t_brand',
        ),
        migrations.AlterModelTable(
            name='catagory',
            table='t_catagory',
        ),
        migrations.AlterModelTable(
            name='repair',
            table='t_repair',
        ),
    ]
