# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0003_auto_20160723_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='ass_acceptDeadline',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
