# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assets_ass_acceptdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_detail',
            name='ass_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.date(2016, 7, 24)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.date(2016, 7, 24)),
        ),
    ]
