# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20160725_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.date(2016, 7, 27)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.date(2016, 7, 27)),
        ),
    ]
