# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20160730_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets_detail',
            options={'ordering': ['ass_id', 'ass_operDate']},
        ),
    ]
