# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 18:54
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0013_auto_20160819_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 18, 54, 13, 662000)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 20, 18, 54, 13, 667000),
                                       null=True),
        ),
    ]
