# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20160820_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='ass_SN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='ass_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_billPic',
            field=models.ImageField(blank=True, null=True, upload_to='static/billPic'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 22, 5, 37, 17000)),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/pic'),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 24, 22, 5, 37, 20000), null=True),
        ),
    ]
