# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20160824_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_delflag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cate_delflag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 20, 49, 42, 382000)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 29, 20, 49, 42, 386000), null=True),
        ),
    ]
