# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 14:43
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0017_auto_20160902_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets_detail',
            name='ass_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 14, 43, 26, 379000)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 3, 14, 43, 26, 384000),
                                       null=True),
        ),
    ]
