# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 16:39
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0018_auto_20160903_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='re_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='re_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 16, 39, 22, 887000)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 3, 16, 39, 22, 890000),
                                       null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='re_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='re_operator',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='re_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
