# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 22:28
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0019_auto_20160903_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 22, 28, 27, 396000)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 24, 22, 28, 27, 400000),
                                       null=True),
        ),
    ]
