# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_auto_20160924_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='ass_archiveNO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='ass_operDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 22, 32, 48, 480000)),
        ),
        migrations.AlterField(
            model_name='assets_detail',
            name='ass_operDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 24, 22, 32, 48, 486000), null=True),
        ),
    ]
